#!/bin/bash
########################################################################
#
#  This file is part of colibri-earlyboot.
#  
#  Copyright (C) 2016	Daniel Kesler <kesler.daniel@gmail.com>
#  
#  Foobar is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  Foobar is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

. /lib/colibrikitlib
. /lib/.config
. /lib/.user_config
. /lib/.product.sh

RC=$(cat /run/rc.earlyboot)

if [ "$RC" == "poweroff" ]; then
	/sbin/poweroff -f
elif [ "$RC" == "reboot" ]; then
	change_root "$UNION"
elif [ "$RC" == "update" ]; then
	# umount bundles
	echo "Updating System..."
	sleep 1
	# call update_procedure
	echo "Booting System..."
	# remount bundles
	change_root "$UNION"
elif [ "$RC" == "console" ]; then
	init_proc_sysfs
	/bin/bash
fi

