#!/bin/bash
########################################################################
#
#  This file is part of colibri-earlyboot.
#  
#  Copyright (C) 2016	Daniel Kesler <kesler.daniel@gmail.com>
#  
#  colibri-earlyboot is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  colibri-earlyboot is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

export PATH=.:/:/usr/sbin:/usr/bin:/sbin:/bin

. /lib/colibrikitlib
. /lib/.config
. /lib/.user_config
. /lib/.product.sh

RC=$(cat /run/rc.earlyboot)

case $RC in
	poweroff)
		/sbin/poweroff -f
		;;
	reboot)
		/sbin/reboot -f
		;;
	soft-reboot)
		change_root "$UNION"
		;;
	update)
		
		init_proc_sysfs
		# Un-mount all bundles
		remove_all_bundles
		
		echo "Updating System..."
	
		# 1) Remount the bundles partitions as read-write
		mount -o rw,remount $BUNDLES
		# 2) Execute postponed operations
		rearrange_bundles "$BUNDLES"
		# 3) Remount the bundles partitions as read-only
		mount -o ro,remount $BUNDLES
		sleep 5
		
		# init aufs union
		init_union "$CHANGES" "$UNION"
		# Remount bundles
		union_append_bundles "$BUNDLES" "$BDATA" "$UNION"
		
		echo "Booting System..."
		cleanup_proc_sysfs
		
		change_root "$UNION"
		;;
	console)
		init_proc_sysfs
		/bin/bash
		;;
	*)
		echo "Unsupported run level"
		init_proc_sysfs
		/bin/bash		
		;;
esac
